### ISSUE TITLE
systematic Agilent GCMS data documentation

### ISSUE THREAD

**Issue by blakeboswell** [audere-labs/pyvalence#14]
I'm uncomfortable with our rigor around the Agilent GCMS data files.  This could be because i'm not steeped in the domain.  It would be beneficial to internally document `valence` build coverage with respect to:

1. Exactly what Agilent devices are we targeting?
2. A comprehensive list of the output files these devices produce.
  - Is the `.D` directory comprehensive?
  - What files can appear in a `.D` directory? Other directories?
  - What data is contained in these files? Other directories?

We can prioritize implementation of what's important, and move onto other devices/analytical methods before implementing comprehensive Agilent coverage.  However, a checklist of the universe of possible files to reference would be highly beneficial for development and design purposes.

**Comment by wilsoa6** [comment]
Need to add in reference to agilent gcms software in documentation

**Comment by wilsoa6** [comment]
Ive updated the markdown file, it will continue to evolve, not sure if you want to close this issue or leave it open for discussions
